import SwiftUI

/// Generated by scripts/sync-design-tokens.ts
/// Source of truth: packages/shared/src/theme.ts
struct BrandTextStyle: Sendable {
    let size: CGFloat
    let weight: Font.Weight
    let lineHeightMultiple: CGFloat
    let trackingEm: CGFloat
}

struct BrandShadowLayer: Sendable {
    let color: Color
    let opacity: Double
    let radius: CGFloat
    let x: CGFloat
    let y: CGFloat
}

struct BrandShadowToken: Sendable {
    let layers: [BrandShadowLayer]
}

enum BrandTheme {
    enum Palette {
        static let primary50 = Color(hex: 0xE5F1FF, opacity: 1.0)
        static let primary100 = Color(hex: 0xC7E1FF, opacity: 1.0)
        static let primary200 = Color(hex: 0x78B6FC, opacity: 1.0)
        static let primary300 = Color(hex: 0x4A94E8, opacity: 1.0)
        static let primary400 = Color(hex: 0x0F6FDE, opacity: 1.0)
        static let primary500 = Color(hex: 0x0D62C4, opacity: 1.0)
        static let primary600 = Color(hex: 0x0B5BB8, opacity: 1.0)
        static let primary700 = Color(hex: 0x052D5B, opacity: 1.0)
        static let primary800 = Color(hex: 0x030E1D, opacity: 1.0)
        static let primary900 = Color(hex: 0x020A16, opacity: 1.0)
        static let accent50 = Color(hex: 0xE6FBF8, opacity: 1.0)
        static let accent100 = Color(hex: 0xCCF5EF, opacity: 1.0)
        static let accent200 = Color(hex: 0x99EBE0, opacity: 1.0)
        static let accent300 = Color(hex: 0x66E1D0, opacity: 1.0)
        static let accent400 = Color(hex: 0x33D4C1, opacity: 1.0)
        static let accent500 = Color(hex: 0x00C4AC, opacity: 1.0)
        static let accent600 = Color(hex: 0x009B87, opacity: 1.0)
        static let accent700 = Color(hex: 0x007A6B, opacity: 1.0)
        static let accent800 = Color(hex: 0x005A4F, opacity: 1.0)
        static let accent900 = Color(hex: 0x003A33, opacity: 1.0)
        static let secondary50 = Color(hex: 0xF5F3FF, opacity: 1.0)
        static let secondary100 = Color(hex: 0xEDE9FE, opacity: 1.0)
        static let secondary200 = Color(hex: 0xDDD6FE, opacity: 1.0)
        static let secondary300 = Color(hex: 0xC4B5FD, opacity: 1.0)
        static let secondary400 = Color(hex: 0xA78BFA, opacity: 1.0)
        static let secondary500 = Color(hex: 0x8B5CF6, opacity: 1.0)
        static let secondary600 = Color(hex: 0x7C3AED, opacity: 1.0)
        static let secondary700 = Color(hex: 0x3A2899, opacity: 1.0)
        static let secondary800 = Color(hex: 0x2A1D70, opacity: 1.0)
        static let secondary900 = Color(hex: 0x21175A, opacity: 1.0)
        static let success50 = Color(hex: 0xECFDF5, opacity: 1.0)
        static let success100 = Color(hex: 0xD1FAE5, opacity: 1.0)
        static let success500 = Color(hex: 0x10BC4C, opacity: 1.0)
        static let success700 = Color(hex: 0x0A8F3A, opacity: 1.0)
        static let warning50 = Color(hex: 0xFFFBEB, opacity: 1.0)
        static let warning100 = Color(hex: 0xFEF3C7, opacity: 1.0)
        static let warning500 = Color(hex: 0xFFB60A, opacity: 1.0)
        static let warning700 = Color(hex: 0xCC9208, opacity: 1.0)
        static let error50 = Color(hex: 0xFEF2F2, opacity: 1.0)
        static let error100 = Color(hex: 0xFEE2E2, opacity: 1.0)
        static let error500 = Color(hex: 0xEF4444, opacity: 1.0)
        static let error700 = Color(hex: 0xB91C1C, opacity: 1.0)
        static let info50 = Color(hex: 0xE5F1FF, opacity: 1.0)
        static let info100 = Color(hex: 0xC7E1FF, opacity: 1.0)
        static let info500 = Color(hex: 0x0F6FDE, opacity: 1.0)
        static let info700 = Color(hex: 0x0B5BB8, opacity: 1.0)
        static let neutral50 = Color(hex: 0xF8F9FC, opacity: 1.0)
        static let neutral100 = Color(hex: 0xF5F6F9, opacity: 1.0)
        static let neutral200 = Color(hex: 0xECEFF4, opacity: 1.0)
        static let neutral300 = Color(hex: 0xE0E5EB, opacity: 1.0)
        static let neutral400 = Color(hex: 0xA0AABD, opacity: 1.0)
        static let neutral500 = Color(hex: 0x556272, opacity: 1.0)
        static let neutral600 = Color(hex: 0x364153, opacity: 1.0)
        static let neutral700 = Color(hex: 0x1E1A37, opacity: 1.0)
        static let neutral800 = Color(hex: 0x030E1D, opacity: 1.0)
        static let neutral900 = Color(hex: 0x020A16, opacity: 1.0)
        static let neutral950 = Color(hex: 0x01040B, opacity: 1.0)
        static let surfaceCanvas = Color(hex: 0xFFFFFF, opacity: 1.0)
        static let surfaceSubtle = Color(hex: 0xF8F9FC, opacity: 1.0)
        static let surfaceMuted = Color(hex: 0xF5F6F9, opacity: 1.0)
        static let surfaceRaised = Color(hex: 0xFFFFFF, opacity: 1.0)
        static let surfaceBrand = Color(hex: 0xE5F1FF, opacity: 1.0)
        static let surfaceAccent = Color(hex: 0xE6FBF8, opacity: 1.0)
        static let surfaceInverse = Color(hex: 0x030E1D, opacity: 1.0)
        static let surfaceOverlay = Color(hex: 0x020A16, opacity: 0.70)
    }

    enum SemanticColor {
        static let textPrimary = Color(hex: 0x030E1D, opacity: 1.0)
        static let textSecondary = Color(hex: 0x364153, opacity: 1.0)
        static let textMuted = Color(hex: 0x556272, opacity: 1.0)
        static let textInverse = Color(hex: 0xF8F9FC, opacity: 1.0)
        static let textBrand = Color(hex: 0x052D5B, opacity: 1.0)
        static let surfaceCanvas = Color(hex: 0xFFFFFF, opacity: 1.0)
        static let surfaceSubtle = Color(hex: 0xF8F9FC, opacity: 1.0)
        static let surfaceCard = Color(hex: 0xFFFFFF, opacity: 1.0)
        static let surfaceMuted = Color(hex: 0xF5F6F9, opacity: 1.0)
        static let surfaceBrand = Color(hex: 0xE5F1FF, opacity: 1.0)
        static let surfaceAccent = Color(hex: 0xE6FBF8, opacity: 1.0)
        static let surfaceInverse = Color(hex: 0x030E1D, opacity: 1.0)
        static let surfaceOverlay = Color(hex: 0x020A16, opacity: 0.70)
        static let borderDefault = Color(hex: 0xECEFF4, opacity: 1.0)
        static let borderStrong = Color(hex: 0xE0E5EB, opacity: 1.0)
        static let borderFocus = Color(hex: 0x0F6FDE, opacity: 1.0)
        static let borderAccent = Color(hex: 0x00C4AC, opacity: 1.0)
        static let actionPrimary = Color(hex: 0x052D5B, opacity: 1.0)
        static let actionPrimaryHover = Color(hex: 0x0B5BB8, opacity: 1.0)
        static let actionAccent = Color(hex: 0x00C4AC, opacity: 1.0)
        static let actionAccentHover = Color(hex: 0x009B87, opacity: 1.0)
        static let statusSuccess = Color(hex: 0x10BC4C, opacity: 1.0)
        static let statusWarning = Color(hex: 0xFFB60A, opacity: 1.0)
        static let statusError = Color(hex: 0xEF4444, opacity: 1.0)
        static let statusInfo = Color(hex: 0x0F6FDE, opacity: 1.0)
    }

    enum Spacing {
        static let stackTight: CGFloat = 12
        static let stackDefault: CGFloat = 24
        static let stackLoose: CGFloat = 32
        static let inlineTight: CGFloat = 8
        static let inlineDefault: CGFloat = 12
        static let controlX: CGFloat = 20
        static let controlY: CGFloat = 12
        static let cardPadding: CGFloat = 24
        static let cardPaddingDense: CGFloat = 20
        static let sectionPadding: CGFloat = 64
        static let sectionPaddingDense: CGFloat = 48
        static let sectionPaddingHero: CGFloat = 80
        static let pagePaddingMobile: CGFloat = 24
        static let pagePaddingDesktop: CGFloat = 32
        static let gridGap: CGFloat = 32
    }

    enum Radius {
        static let control: CGFloat = 12
        static let card: CGFloat = 16
        static let panel: CGFloat = 24
        static let overlay: CGFloat = 32
        static let pill: CGFloat = 9999
    }

    enum Layout {
        static let containerMax: CGFloat = 1248
        static let contentMax: CGFloat = 1120
        static let navHeight: CGFloat = 80
        static let heroInputHeight: CGFloat = 68
        static let heroCtaHeight: CGFloat = 64
        static let sidebarWidth: CGFloat = 260
        static let sidebarWidthCollapsed: CGFloat = 64
        static let pagePaddingMobile: CGFloat = 24
        static let pagePaddingDesktop: CGFloat = 32
        static let sectionPaddingCompact: CGFloat = 48
        static let sectionPaddingStandard: CGFloat = 64
        static let sectionPaddingGenerous: CGFloat = 80
        static let gridGapCompact: CGFloat = 24
        static let gridGapStandard: CGFloat = 32
    }

    enum Motion {
        static let baseFastDuration: Double = 0.15
        static let baseNormalDuration: Double = 0.25
        static let baseSlowDuration: Double = 0.4
        static let basePageDuration: Double = 0.6
        static let interactiveDuration: Double = 0.15
        static let surfaceDuration: Double = 0.25
        static let pageDuration: Double = 0.6
        static let interactiveEasing = "cubic-bezier(0.4, 0, 0.2, 1)"
        static let entranceEasing = "cubic-bezier(0.16, 1, 0.3, 1)"
        static let emphasisEasing = "cubic-bezier(0.34, 1.56, 0.64, 1)"
    }

    enum Typography {
        static let sans = "\"Inter\", system-ui, -apple-system, sans-serif"
        static let mono = "\"JetBrains Mono\", \"Fira Code\", monospace"
        static let eyebrow = BrandTextStyle(size: 14, weight: .semibold, lineHeightMultiple: 1.5, trackingEm: 0.05)
        static let body = BrandTextStyle(size: 16, weight: .regular, lineHeightMultiple: 1.5, trackingEm: 0)
        static let bodyLead = BrandTextStyle(size: 18, weight: .regular, lineHeightMultiple: 1.6, trackingEm: 0)
        static let heading = BrandTextStyle(size: 24, weight: .semibold, lineHeightMultiple: 1.15, trackingEm: -0.006)
        static let display = BrandTextStyle(size: 52, weight: .semibold, lineHeightMultiple: 1.15, trackingEm: -0.02)
        static let caption = BrandTextStyle(size: 12, weight: .medium, lineHeightMultiple: 1.5, trackingEm: 0)
    }

    enum Shadow {
        static let card = BrandShadowToken(layers: [BrandShadowLayer(color: Color(hex: 0x020A16), opacity: 0.05, radius: 2, x: 0, y: 1)])
        static let interactive = BrandShadowToken(layers: [BrandShadowLayer(color: Color(hex: 0x020A16), opacity: 0.10, radius: 6, x: 0, y: 4), BrandShadowLayer(color: Color(hex: 0x020A16), opacity: 0.10, radius: 4, x: 0, y: 2)])
        static let floating = BrandShadowToken(layers: [BrandShadowLayer(color: Color(hex: 0x020A16), opacity: 0.12, radius: 15, x: 0, y: 10), BrandShadowLayer(color: Color(hex: 0x020A16), opacity: 0.12, radius: 6, x: 0, y: 4)])
        static let overlay = BrandShadowToken(layers: [BrandShadowLayer(color: Color(hex: 0x020A16), opacity: 0.16, radius: 25, x: 0, y: 20), BrandShadowLayer(color: Color(hex: 0x020A16), opacity: 0.08, radius: 10, x: 0, y: 10)])
    }
}
