import type {
  DashboardActiveDealRow,
  DashboardRecentDealRow,
  DashboardSummaryBadge,
} from "@/lib/dashboard/deal-index";
import {
  buildAdvisorySurfaceState,
  summarizeAdvisoryEvidence,
} from "@/lib/advisory/surface-state";
import type { BuyerDashboardState } from "@/lib/dashboard/deal-index-state";
import type { PropertyCaseOverviewSurface } from "@/lib/dealroom/property-case-overview";

const previewSummaryBadges: DashboardSummaryBadge[] = [
  {
    kind: "active_count",
    label: "Active deal rooms",
    tone: "primary",
    value: "3",
    isEmpty: false,
  },
  {
    kind: "recent_count",
    label: "Recently wrapped",
    tone: "neutral",
    value: "1",
    isEmpty: false,
  },
  {
    kind: "most_urgent",
    label: "Most urgent",
    tone: "warning",
    value: "Offer prep",
    isEmpty: false,
  },
  {
    kind: "oldest_active",
    label: "Longest open",
    tone: "neutral",
    value: "6 days",
    isEmpty: false,
  },
];

const previewActiveDeals: DashboardActiveDealRow[] = [
  {
    category: "active",
    dealRoomId: "preview-miami-beach",
    propertyId: "preview-property-1",
    status: "offer_prep",
    urgencyRank: 3,
    addressLine: "123 Gulf Stream Ave, Miami Beach, FL 33139",
    listPrice: 965000,
    beds: 4,
    baths: 3.5,
    sqft: 2840,
    primaryPhotoUrl: "/images/marketing/hero/product-dashboard.png",
    score: 9.2,
    scoreSource: "offer_competitiveness",
    accessLevel: "full",
    updatedAt: "2026-04-13T14:10:00.000Z",
    detailState: "complete",
    missingFields: [],
  },
  {
    category: "active",
    dealRoomId: "preview-coral-gables",
    propertyId: "preview-property-2",
    status: "analysis",
    urgencyRank: 6,
    addressLine: "814 Alhambra Cir, Coral Gables, FL 33134",
    listPrice: 1245000,
    beds: 5,
    baths: 4,
    sqft: 3375,
    primaryPhotoUrl: "/images/marketing/features/feature-2.png",
    score: 8.6,
    scoreSource: "leverage",
    accessLevel: "registered",
    updatedAt: "2026-04-13T11:45:00.000Z",
    detailState: "complete",
    missingFields: [],
  },
  {
    category: "active",
    dealRoomId: "preview-tampa",
    propertyId: "preview-property-3",
    status: "tour_scheduled",
    urgencyRank: 5,
    addressLine: "42 Bayshore Blvd, Tampa, FL 33606",
    listPrice: 735000,
    beds: 3,
    baths: 2,
    sqft: 1940,
    primaryPhotoUrl: "/images/marketing/bento/bento-2.png",
    score: 7.8,
    scoreSource: "leverage",
    accessLevel: "registered",
    updatedAt: "2026-04-12T18:35:00.000Z",
    detailState: "complete",
    missingFields: [],
  },
];

const previewRecentDeals: DashboardRecentDealRow[] = [
  {
    category: "recent",
    dealRoomId: "preview-orlando",
    propertyId: "preview-property-4",
    status: "closed",
    urgencyRank: 7,
    addressLine: "88 Lake Eola Dr, Orlando, FL 32801",
    listPrice: 682000,
    beds: 3,
    baths: 2.5,
    sqft: 2105,
    primaryPhotoUrl: "/images/marketing/bento/bento-1.png",
    score: 8.9,
    scoreSource: "offer_competitiveness",
    accessLevel: "full",
    updatedAt: "2026-04-11T09:20:00.000Z",
    detailState: "complete",
    missingFields: [],
  },
];

export const previewBuyerDashboardState: BuyerDashboardState = {
  kind: "ready",
  activeDeals: previewActiveDeals,
  recentDeals: previewRecentDeals,
  summaryBadges: previewSummaryBadges,
  hasPartialDeals: false,
};

const previewMemoEvidence = summarizeAdvisoryEvidence([
  {
    status: "supported",
    confidenceBand: "medium",
    supportLabels: ["portal estimates", "recent comparable sales"],
    missingLabels: [],
    conflictingLabels: [],
    caution: null,
    dependsOnInference: false,
  },
  {
    status: "mixed",
    confidenceBand: "medium",
    supportLabels: ["market context", "listing history"],
    missingLabels: ["seller posture refresh"],
    conflictingLabels: [],
    caution: "Still waiting on seller posture refresh.",
    dependsOnInference: false,
  },
]);

const previewRecommendationEvidence = summarizeAdvisoryEvidence([
  {
    status: "mixed",
    confidenceBand: "medium",
    supportLabels: ["pricing output", "offer strategy"],
    missingLabels: ["fresh broker review"],
    conflictingLabels: [],
    caution: "Still waiting on fresh broker review.",
    dependsOnInference: true,
  },
]);

export const previewPropertyCaseOverview: PropertyCaseOverviewSurface = {
  variant: "buyer_safe",
  viewerRole: "buyer",
  dealRoomId: "preview-miami-beach",
  propertyId: "preview-property-1",
  propertyAddress: "123 Gulf Stream Ave, Miami Beach, FL 33139",
  listPrice: 965000,
  listPriceLabel: "$965,000",
  photoUrl: "/images/marketing/hero/product-dashboard.png",
  status: {
    status: "offer_prep",
    label: "Offer prep",
    tone: "warning",
    nextAction: "Review the opening range with your broker",
  },
  viewState: "ready",
  generatedAt: "2026-04-13T15:15:00.000Z",
  generatedAtLabel: "Updated Apr 13",
  advisoryVersion: {
    synthesisVersion: "1.0.0",
    artifactGeneratedAt: "2026-04-13T15:15:00.000Z",
  },
  confidenceFingerprint: "evidence-graph-preview-v1",
  confidenceReplayKey: "dealroom-preview-123",
  overallConfidence: 0.78,
  overallConfidenceLabel: "78% confidence",
  overallConfidenceTone: "strong",
  coverageStats: {
    availableCount: 3,
    pendingCount: 1,
    uncertainCount: 0,
    missingCount: 0,
  },
  coverageSummary:
    "Pricing, comps, and leverage are approved for the buyer-safe case. Offer strategy stays visible with one pending citation refresh.",
  headerDescription:
    "The asking price is still above the strongest comparable cluster, but the leverage signals are positive enough to support a disciplined opening number instead of a full-price start.",
  marketReality: {
    geographyLabel: "Subdivision · Palm Estates",
    marketWindowLabel: "90-day market window",
    fallbackNotice: null,
    sampleSizeLabel: "6 sold / 12 total records",
    freshnessLabel: "Fresh · 30m old",
    reliabilityLabel: "High reliability",
    position: {
      code: "overpriced",
      label: "Overpriced for this market",
      summary:
        "This listing is asking more per sqft than the local norm for the selected market slice.",
      tone: "warning",
    },
    signals: [
      {
        key: "days_on_market",
        label: "Days on market",
        status: "available",
        tone: "warning",
        summary: "This home has been on market longer than typical for this subdivision.",
        subjectLabel: "39 days",
        baselineLabel: "28 day local median",
        deltaLabel: "+39.3% vs local median (+11 days)",
      },
      {
        key: "price_per_sqft",
        label: "Price per sqft",
        status: "available",
        tone: "warning",
        summary: "The asking price per sqft is above the local norm.",
        subjectLabel: "$340/sqft",
        baselineLabel: "$315/sqft median · $320/sqft avg",
        deltaLabel: "+7.9% vs local median",
      },
      {
        key: "sale_to_list",
        label: "Sale-to-list behavior",
        status: "available",
        tone: "positive",
        summary: "Homes here usually close meaningfully below asking.",
        subjectLabel: null,
        baselineLabel: "96.8% median close-to-ask",
        deltaLabel: "97.2% avg",
      },
      {
        key: "price_cuts",
        label: "Price-cut behavior",
        status: "available",
        tone: "positive",
        summary:
          "This listing has already cut price 1 time, while about 38% of local listings cut at all.",
        subjectLabel: "1 cut · $20,000 total (2%) · last cut 9d ago",
        baselineLabel: "38% of local listings cut · 2.6% median cut",
        deltaLabel: null,
      },
    ],
  },
  decisionMemo: {
    title: "Why this home / why not this home",
    summary:
      "Offer prep. The current memo has enough evidence to show the upside, the downside, and a clear recommendation in one place.",
    upside: {
      title: "Why this home could be worth pursuing",
      summary: "These points are carrying the buyer-safe case right now.",
      items: [
        {
          id: "preview-upside-dom",
          title: "Time on market",
          body:
            "Time on market and the latest price adjustment both suggest the seller is prioritizing momentum over waiting for a premium bid.",
          evidence: [
            {
              id: "preview-upside-dom-evidence",
              label: "39 days on market vs 28 day local median",
              citationId: "dom-2026-04-13-01",
              sourceAnchorId: "source-dom-2026-04-13-01",
              nodeId: null,
              confidenceLabel: "74% confidence",
              statusLabel: null,
              provenance: [],
            },
          ],
        },
      ],
    },
    downside: {
      title: "Why this home may be risky or overpriced",
      summary:
        "These are the strongest reasons to stay disciplined instead of treating the home as an obvious yes.",
      items: [
        {
          id: "preview-downside-pricing",
          title: "Pricing",
          body:
            "The listing is trending above the closest renovated comparable set, which creates room for a measured first offer instead of a full-price opener.",
          evidence: [
            {
              id: "preview-downside-pricing-evidence",
              label: "$965,000 vs $926,000 renovated comparable average",
              citationId: "pricing-2026-04-13-01",
              sourceAnchorId: "source-pricing-2026-04-13-01",
              nodeId: null,
              confidenceLabel: "82% confidence",
              statusLabel: "Supported",
              provenance: [],
            },
          ],
        },
      ],
    },
    unknowns: {
      title: "What we still do not know",
      summary:
        "These gaps should change how much confidence you place in the memo today.",
      items: [
        {
          id: "preview-unknown-offer",
          title: "Offer pack refresh is still running",
          body:
            "The refreshed counter-scenario set is still being prepared, so the buyer-safe case holds the current opener until the next pass lands.",
          evidence: [
            {
              id: "preview-unknown-offer-evidence",
              label: "Offer strategy",
              citationId: null,
              sourceAnchorId: null,
              nodeId: null,
              confidenceLabel: null,
              statusLabel: "Waiting on evidence",
              provenance: [],
            },
          ],
        },
      ],
    },
    unresolvedRisks: {
      title: "Unresolved risks and review-required items",
      summary:
        "These issues are visible, but they still need diligence or human review before the case is fully settled.",
      items: [
        {
          id: "preview-risk",
          title: "Risk",
          body:
            "The biggest known risks are visible, but they still need normal diligence.",
          evidence: [
            {
              id: "preview-risk-evidence",
              label: "document findings",
              citationId: null,
              sourceAnchorId: null,
              nodeId: null,
              confidenceLabel: "71% confidence",
              statusLabel: "Supported",
              provenance: [],
            },
          ],
        },
      ],
    },
    recommendation: {
      verdict: "pursue_with_caution",
      label: "Current recommendation",
      body:
        "Treat the home as worth pursuing only with a disciplined opener around $928,000. Use this as an illustrative starting point and confirm the final strategy with your broker.",
      confidenceLabel: "73% action confidence",
      riskLabel: "Medium risk",
      openingPriceLabel: "$928,000",
      evidence: [
        {
          id: "preview-recommendation-evidence",
          label: "pricing support",
          citationId: null,
          sourceAnchorId: null,
          nodeId: null,
          confidenceLabel: null,
          statusLabel: "Waiting on evidence",
          provenance: [],
        },
      ],
    },
  },
  confidenceSections: [
    {
      key: "pricing",
      title: "Pricing",
      band: "high",
      bandLabel: "High confidence",
      score: 0.82,
      scoreLabel: "82% confidence",
      tone: "strong",
      status: "supported",
      statusLabel: "Supported",
      buyerHeadline:
        "Pricing is anchored by aligned estimate and comp evidence.",
      buyerExplanation:
        "Pricing is anchored by aligned estimate and comp evidence. The current evidence is aligned enough to show this in the buyer-safe view.",
      strongEvidence: [
        "portal estimate consensus",
        "recent renovated comparable sales",
      ],
      missingEvidence: [],
      contradictoryEvidence: [],
      whatWouldIncreaseConfidence: [
        "Keep the cited evidence fresh before finalizing the decision.",
      ],
      dependsOnInference: false,
    },
    {
      key: "comps",
      title: "Comparable sales",
      band: "medium",
      bandLabel: "Moderate confidence",
      score: 0.74,
      scoreLabel: "74% confidence",
      tone: "mixed",
      status: "mixed",
      statusLabel: "Mixed evidence",
      buyerHeadline:
        "The closest comparable set supports a below-ask opener, but the sample is still tight.",
      buyerExplanation:
        "The closest comparable set supports a below-ask opener, but the sample is still tight. Some of this still depends on inferred signals instead of fully verified records.",
      strongEvidence: ["recent sold comps", "market-context baseline"],
      missingEvidence: ["more verified local sold comps"],
      contradictoryEvidence: [],
      whatWouldIncreaseConfidence: ["Add more verified local sold comps."],
      dependsOnInference: true,
    },
    {
      key: "leverage",
      title: "Negotiation leverage",
      band: "medium",
      bandLabel: "Moderate confidence",
      score: 0.69,
      scoreLabel: "69% confidence",
      tone: "mixed",
      status: "mixed",
      statusLabel: "Mixed evidence",
      buyerHeadline:
        "Seller timing signals are helpful, but they are not fully one-directional yet.",
      buyerExplanation:
        "Seller timing signals are helpful, but they are not fully one-directional yet. Some of this still depends on inferred signals instead of fully verified records.",
      strongEvidence: ["days on market", "recent price-cut history"],
      missingEvidence: ["fresh neighborhood baselines"],
      contradictoryEvidence: ["conflicting listing-history inputs"],
      whatWouldIncreaseConfidence: [
        "Add fresh neighborhood baselines.",
        "Resolve the conflict around conflicting listing-history inputs.",
      ],
      dependsOnInference: true,
    },
    {
      key: "risk",
      title: "Risk",
      band: "medium",
      bandLabel: "Moderate confidence",
      score: 0.71,
      scoreLabel: "71% confidence",
      tone: "mixed",
      status: "supported",
      statusLabel: "Supported",
      buyerHeadline:
        "The biggest known risks are visible, but they still need normal diligence.",
      buyerExplanation:
        "The biggest known risks are visible, but they still need normal diligence. The current evidence is aligned enough to show this in the buyer-safe view.",
      strongEvidence: ["document findings", "risk hooks"],
      missingEvidence: [],
      contradictoryEvidence: [],
      whatWouldIncreaseConfidence: [
        "Keep the cited evidence fresh before finalizing the decision.",
      ],
      dependsOnInference: false,
    },
    {
      key: "offer_recommendation",
      title: "Offer recommendation",
      band: "medium",
      bandLabel: "Moderate confidence",
      score: 0.73,
      scoreLabel: "73% confidence",
      tone: "mixed",
      status: "waiting_on_evidence",
      statusLabel: "Waiting on evidence",
      buyerHeadline:
        "The recommended opener is directionally grounded, but one refresh is still pending.",
      buyerExplanation:
        "The recommended opener is directionally grounded, but one refresh is still pending. The refreshed scenario set is not fully locked yet.",
      strongEvidence: ["pricing support", "seller-timing leverage"],
      missingEvidence: ["fresh offer-scenario refresh"],
      contradictoryEvidence: [],
      whatWouldIncreaseConfidence: ["Add fresh offer-scenario refresh."],
      dependsOnInference: false,
    },
  ],
  artifacts: {
    memo: buildAdvisorySurfaceState({
      surface: "memo",
      evidence: previewMemoEvidence,
      hasRenderableContent: true,
    }),
    recommendation: buildAdvisorySurfaceState({
      surface: "recommendation",
      evidence: previewRecommendationEvidence,
      hasRenderableContent: true,
    }),
    playbook: buildAdvisorySurfaceState({
      surface: "playbook",
      evidence: previewRecommendationEvidence,
      hasRenderableContent: true,
    }),
    summary: buildAdvisorySurfaceState({
      surface: "summary",
      evidence: summarizeAdvisoryEvidence([
        previewMemoEvidence,
        previewRecommendationEvidence,
      ]),
      hasRenderableContent: true,
    }),
  },
  claims: [
    {
      id: "preview-claim-pricing",
      topic: "pricing",
      topicLabel: "Pricing",
      narrative:
        "The listing is trending above the closest renovated comparable set, which creates room for a measured first offer instead of a full-price opener.",
      deltaLabel: "4.2% above nearby renovated comps",
      referenceLine: "$965,000 vs $926,000 renovated comparable average",
      confidence: 0.82,
      confidenceLabel: "82% confidence",
      confidenceTone: "strong",
      citationId: "pricing-2026-04-13-01",
      sourceAnchorId: "source-pricing-2026-04-13-01",
      guardrailState: "softened",
      guardrailLabel: "Softened",
    },
    {
      id: "preview-claim-dom",
      topic: "days_on_market",
      topicLabel: "Time on market",
      narrative:
        "Time on market and the latest price adjustment both suggest the seller is prioritizing momentum over waiting for a premium bid.",
      deltaLabel: "11 days above local median DOM",
      referenceLine: "39 days on market vs 28 day local median",
      confidence: 0.74,
      confidenceLabel: "74% confidence",
      confidenceTone: "mixed",
      citationId: "dom-2026-04-13-01",
      sourceAnchorId: "source-dom-2026-04-13-01",
      guardrailState: "softened",
      guardrailLabel: "Softened",
    },
    {
      id: "preview-claim-leverage",
      topic: "leverage",
      topicLabel: "Negotiation leverage",
      narrative:
        "Buyer leverage improves if the offer is framed around clean financing and a fast inspection window rather than a large concession list.",
      deltaLabel: "In line with recent seller-side leverage wins",
      referenceLine: "Strong financing terms vs recent accepted Miami Beach offers",
      confidence: 0.69,
      confidenceLabel: "69% confidence",
      confidenceTone: "mixed",
      citationId: "leverage-2026-04-13-01",
      sourceAnchorId: "source-leverage-2026-04-13-01",
      guardrailState: "softened",
      guardrailLabel: "Softened",
    },
  ],
  keyTakeaways: [
    {
      title: "Pricing",
      body: "The best comparable cluster still supports a first number below ask without looking unserious.",
    },
    {
      title: "Seller posture",
      body: "Price movement and time on market indicate the seller is likely balancing certainty against holding out for a premium.",
    },
    {
      title: "Negotiation shape",
      body: "A clean inspection window and financing clarity are more persuasive than stacking extra asks into the first draft.",
    },
  ],
  action: {
    openingPrice: 928000,
    openingPriceLabel: "$928,000",
    confidence: 0.73,
    confidenceLabel: "73% action confidence",
    riskLevel: "medium",
    riskLabel: "Medium risk",
    suggestedContingencies: [
      "Standard inspection",
      "Financing contingency",
      "Appraisal gap review",
    ],
    rationale: [
      {
        title: "Comparable gap",
        body: "Recent renovated comps cluster below ask, so the first move can anchor lower without being outside the evidence band.",
      },
      {
        title: "Seller timing",
        body: "Days on market are long enough to justify a deliberate opener, especially if execution risk stays low.",
      },
    ],
    guardrailState: "softened",
    guardrailLabel: "Softened",
    guardrailExplanation:
      "Use this as an illustrative starting point and confirm the final strategy with your broker.",
    reviewedConclusion: null,
    buyerExplanation: null,
    isBrokerReviewed: false,
  },
  missingStates: [
    {
      engine: "offer",
      label: "Offer strategy",
      tone: "pending",
      title: "Offer pack refresh is still running",
      description:
        "The refreshed counter-scenario set is still being prepared, so the buyer-safe case holds the current opener until the next pass lands.",
    },
  ],
  sources: [
    {
      citationId: "pricing-2026-04-13-01",
      anchorId: "source-pricing-2026-04-13-01",
      engineType: "pricing",
      engineLabel: "Pricing engine",
      status: "available",
      reviewState: "approved",
      adjudicationStatus: "approved",
      adjudicationLabel: "Approved as-is",
      visibility: "buyer_safe",
      visibilityLabel: "Buyer-safe",
      reviewedConclusion: null,
      buyerExplanation: null,
      reviewedByLabel: "Preview broker",
      reviewedAtLabel: "Apr 13",
      confidenceLabel: "82% confidence",
      generatedAtLabel: "Apr 13",
      claimCount: 1,
      guardrailState: "softened",
      guardrailLabel: "Softened",
      approvalPath: "none",
    },
    {
      citationId: "dom-2026-04-13-01",
      anchorId: "source-dom-2026-04-13-01",
      engineType: "comps",
      engineLabel: "Comparable sales engine",
      status: "available",
      reviewState: "approved",
      adjudicationStatus: "approved",
      adjudicationLabel: "Approved as-is",
      visibility: "buyer_safe",
      visibilityLabel: "Buyer-safe",
      reviewedConclusion: null,
      buyerExplanation: null,
      reviewedByLabel: "Preview broker",
      reviewedAtLabel: "Apr 13",
      confidenceLabel: "74% confidence",
      generatedAtLabel: "Apr 13",
      claimCount: 1,
      guardrailState: "can_say",
      guardrailLabel: "Buyer-safe",
      approvalPath: "none",
    },
    {
      citationId: "leverage-2026-04-13-01",
      anchorId: "source-leverage-2026-04-13-01",
      engineType: "leverage",
      engineLabel: "Leverage engine",
      status: "available",
      reviewState: "approved",
      adjudicationStatus: "approved",
      adjudicationLabel: "Approved as-is",
      visibility: "buyer_safe",
      visibilityLabel: "Buyer-safe",
      reviewedConclusion: null,
      buyerExplanation: null,
      reviewedByLabel: "Preview broker",
      reviewedAtLabel: "Apr 13",
      confidenceLabel: "69% confidence",
      generatedAtLabel: "Apr 13",
      claimCount: 1,
      guardrailState: "softened",
      guardrailLabel: "Softened",
      approvalPath: "none",
    },
    {
      citationId: "offer-2026-04-13-01",
      anchorId: "source-offer-2026-04-13-01",
      engineType: "offer",
      engineLabel: "Offer strategy engine",
      status: "pending",
      reviewState: "pending",
      adjudicationStatus: "pending",
      adjudicationLabel: "Pending review",
      visibility: null,
      visibilityLabel: null,
      reviewedConclusion: null,
      buyerExplanation: null,
      reviewedByLabel: null,
      reviewedAtLabel: null,
      confidenceLabel: "Refresh running",
      generatedAtLabel: null,
      claimCount: 0,
      guardrailState: "review_required",
      guardrailLabel: "Review required",
      approvalPath: "broker_review",
    },
  ],
};
