import type {
  DashboardActiveDealRow,
  DashboardRecentDealRow,
  DashboardSummaryBadge,
} from "@/lib/dashboard/deal-index";
import type { BuyerDashboardState } from "@/lib/dashboard/deal-index-state";
import type { PropertyCaseOverviewSurface } from "@/lib/dealroom/property-case-overview";

const previewSummaryBadges: DashboardSummaryBadge[] = [
  {
    kind: "active_count",
    label: "Active deal rooms",
    tone: "primary",
    value: "3",
    isEmpty: false,
  },
  {
    kind: "recent_count",
    label: "Recently wrapped",
    tone: "neutral",
    value: "1",
    isEmpty: false,
  },
  {
    kind: "most_urgent",
    label: "Most urgent",
    tone: "warning",
    value: "Offer prep",
    isEmpty: false,
  },
  {
    kind: "oldest_active",
    label: "Longest open",
    tone: "neutral",
    value: "6 days",
    isEmpty: false,
  },
];

const previewActiveDeals: DashboardActiveDealRow[] = [
  {
    category: "active",
    dealRoomId: "preview-miami-beach",
    propertyId: "preview-property-1",
    status: "offer_prep",
    urgencyRank: 3,
    addressLine: "123 Gulf Stream Ave, Miami Beach, FL 33139",
    listPrice: 965000,
    beds: 4,
    baths: 3.5,
    sqft: 2840,
    primaryPhotoUrl: "/images/marketing/hero/product-dashboard.png",
    score: 9.2,
    scoreSource: "offer_competitiveness",
    accessLevel: "full",
    updatedAt: "2026-04-13T14:10:00.000Z",
    detailState: "complete",
    missingFields: [],
  },
  {
    category: "active",
    dealRoomId: "preview-coral-gables",
    propertyId: "preview-property-2",
    status: "analysis",
    urgencyRank: 6,
    addressLine: "814 Alhambra Cir, Coral Gables, FL 33134",
    listPrice: 1245000,
    beds: 5,
    baths: 4,
    sqft: 3375,
    primaryPhotoUrl: "/images/marketing/features/feature-2.png",
    score: 8.6,
    scoreSource: "leverage",
    accessLevel: "registered",
    updatedAt: "2026-04-13T11:45:00.000Z",
    detailState: "complete",
    missingFields: [],
  },
  {
    category: "active",
    dealRoomId: "preview-tampa",
    propertyId: "preview-property-3",
    status: "tour_scheduled",
    urgencyRank: 5,
    addressLine: "42 Bayshore Blvd, Tampa, FL 33606",
    listPrice: 735000,
    beds: 3,
    baths: 2,
    sqft: 1940,
    primaryPhotoUrl: "/images/marketing/bento/bento-2.png",
    score: 7.8,
    scoreSource: "leverage",
    accessLevel: "registered",
    updatedAt: "2026-04-12T18:35:00.000Z",
    detailState: "complete",
    missingFields: [],
  },
];

const previewRecentDeals: DashboardRecentDealRow[] = [
  {
    category: "recent",
    dealRoomId: "preview-orlando",
    propertyId: "preview-property-4",
    status: "closed",
    urgencyRank: 7,
    addressLine: "88 Lake Eola Dr, Orlando, FL 32801",
    listPrice: 682000,
    beds: 3,
    baths: 2.5,
    sqft: 2105,
    primaryPhotoUrl: "/images/marketing/bento/bento-1.png",
    score: 8.9,
    scoreSource: "offer_competitiveness",
    accessLevel: "full",
    updatedAt: "2026-04-11T09:20:00.000Z",
    detailState: "complete",
    missingFields: [],
  },
];

export const previewBuyerDashboardState: BuyerDashboardState = {
  kind: "ready",
  activeDeals: previewActiveDeals,
  recentDeals: previewRecentDeals,
  summaryBadges: previewSummaryBadges,
  hasPartialDeals: false,
};

export const previewPropertyCaseOverview: PropertyCaseOverviewSurface = {
  variant: "buyer_safe",
  dealRoomId: "preview-miami-beach",
  propertyId: "preview-property-1",
  propertyAddress: "123 Gulf Stream Ave, Miami Beach, FL 33139",
  listPrice: 965000,
  listPriceLabel: "$965,000",
  photoUrl: "/images/marketing/hero/product-dashboard.png",
  status: {
    status: "offer_prep",
    label: "Offer prep",
    tone: "warning",
    nextAction: "Review the opening range with your broker",
  },
  viewState: "ready",
  generatedAt: "2026-04-13T15:15:00.000Z",
  generatedAtLabel: "Updated Apr 13",
  overallConfidence: 0.78,
  overallConfidenceLabel: "78% confidence",
  overallConfidenceTone: "strong",
  coverageSummary:
    "Pricing, comps, and leverage are approved for the buyer-safe case. Offer strategy stays visible with one pending citation refresh.",
  headerDescription:
    "The asking price is still above the strongest comparable cluster, but the leverage signals are positive enough to support a disciplined opening number instead of a full-price start.",
  claims: [
    {
      id: "preview-claim-pricing",
      topic: "pricing",
      topicLabel: "Pricing",
      narrative:
        "The listing is trending above the closest renovated comparable set, which creates room for a measured first offer instead of a full-price opener.",
      deltaLabel: "4.2% above nearby renovated comps",
      referenceLine: "$965,000 vs $926,000 renovated comparable average",
      confidence: 0.82,
      confidenceLabel: "82% confidence",
      confidenceTone: "strong",
      citationId: "pricing-2026-04-13-01",
      sourceAnchorId: "source-pricing-2026-04-13-01",
    },
    {
      id: "preview-claim-dom",
      topic: "days_on_market",
      topicLabel: "Time on market",
      narrative:
        "Time on market and the latest price adjustment both suggest the seller is prioritizing momentum over waiting for a premium bid.",
      deltaLabel: "11 days above local median DOM",
      referenceLine: "39 days on market vs 28 day local median",
      confidence: 0.74,
      confidenceLabel: "74% confidence",
      confidenceTone: "mixed",
      citationId: "dom-2026-04-13-01",
      sourceAnchorId: "source-dom-2026-04-13-01",
    },
    {
      id: "preview-claim-leverage",
      topic: "leverage",
      topicLabel: "Negotiation leverage",
      narrative:
        "Buyer leverage improves if the offer is framed around clean financing and a fast inspection window rather than a large concession list.",
      deltaLabel: "In line with recent seller-side leverage wins",
      referenceLine: "Strong financing terms vs recent accepted Miami Beach offers",
      confidence: 0.69,
      confidenceLabel: "69% confidence",
      confidenceTone: "mixed",
      citationId: "leverage-2026-04-13-01",
      sourceAnchorId: "source-leverage-2026-04-13-01",
    },
  ],
  keyTakeaways: [
    {
      title: "Pricing",
      body: "The best comparable cluster still supports a first number below ask without looking unserious.",
    },
    {
      title: "Seller posture",
      body: "Price movement and time on market indicate the seller is likely balancing certainty against holding out for a premium.",
    },
    {
      title: "Negotiation shape",
      body: "A clean inspection window and financing clarity are more persuasive than stacking extra asks into the first draft.",
    },
  ],
  action: {
    openingPrice: 928000,
    openingPriceLabel: "$928,000",
    confidence: 0.73,
    confidenceLabel: "73% action confidence",
    riskLevel: "medium",
    riskLabel: "Medium risk",
    suggestedContingencies: [
      "Standard inspection",
      "Financing contingency",
      "Appraisal gap review",
    ],
    rationale: [
      {
        title: "Comparable gap",
        body: "Recent renovated comps cluster below ask, so the first move can anchor lower without being outside the evidence band.",
      },
      {
        title: "Seller timing",
        body: "Days on market are long enough to justify a deliberate opener, especially if execution risk stays low.",
      },
    ],
  },
  missingStates: [
    {
      engine: "offer",
      label: "Offer strategy",
      tone: "pending",
      title: "Offer pack refresh is still running",
      description:
        "The refreshed counter-scenario set is still being prepared, so the buyer-safe case holds the current opener until the next pass lands.",
    },
  ],
  sources: [
    {
      citationId: "pricing-2026-04-13-01",
      anchorId: "source-pricing-2026-04-13-01",
      engineLabel: "Pricing engine",
      status: "available",
      confidenceLabel: "82% confidence",
      generatedAtLabel: "Apr 13",
      claimCount: 1,
    },
    {
      citationId: "dom-2026-04-13-01",
      anchorId: "source-dom-2026-04-13-01",
      engineLabel: "Comparable sales engine",
      status: "available",
      confidenceLabel: "74% confidence",
      generatedAtLabel: "Apr 13",
      claimCount: 1,
    },
    {
      citationId: "leverage-2026-04-13-01",
      anchorId: "source-leverage-2026-04-13-01",
      engineLabel: "Leverage engine",
      status: "available",
      confidenceLabel: "69% confidence",
      generatedAtLabel: "Apr 13",
      claimCount: 1,
    },
    {
      citationId: "offer-2026-04-13-01",
      anchorId: "source-offer-2026-04-13-01",
      engineLabel: "Offer strategy engine",
      status: "pending",
      confidenceLabel: "Refresh running",
      generatedAtLabel: null,
      claimCount: 0,
    },
  ],
};
